version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./app.Dockerfile
    entrypoint: /app/run.sh
    environment:
      PGHOST: db
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: mysecretpassword
      SKIP_DOWNLOAD: 'skip'
      SKIP_FILTER: 'skip'
    volumes:
      - osmfiles:/data
    depends_on:
      db:
        condition: service_healthy
    container_name: tarmac
    profiles:
      - osm_processing
  tiles:
    image: ghcr.io/maplibre/martin
    container_name: tiles
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@db/postgres
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  api:
    build:
      context: .
      dockerfile: ./api.Dockerfile
    container_name: api
    environment:
      PGHOST: db
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: mysecretpassword
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: .
      dockerfile: ./db.Dockerfile
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    ports:
      - "6000:5432"
    volumes:
      - geodata:/var/lib/postgresql/data
    container_name: osmdatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  geodata:
  osmfiles:
