version: "3"
services:
  geo:
    build:
        context: .
        dockerfile: ./geo.Dockerfile
    command: /geo/run.sh
    container_name: geo
    environment:
      PGHOST:
      PGDATABASE:
      PGUSER:
      PGPASSWORD:
      OSM_DOWNLOAD_URL:
      SKIP_DOWNLOAD:
      SKIP_TAG_FILTER:
      DEBUG:
      ID_FILTER:
      API_SECRET:
      ENVIRONMENT:
      SYNOLOGY_LOG_TOKEN:
      SYNOLOGY_ERROR_LOG_TOKEN:
    volumes:
      - osmfiles:/data
      - type: bind
        source: ./geo
        target: /geo
    networks:
      - app_bridge
volumes:
  geodata:
