services:
  preview:
    image: nginx:stable-alpine
    container_name: preview
    volumes:
    - ./preview/:/usr/share/nginx/html
    ports:
      - 80:80
  tiles:
    image: ghcr.io/maplibre/martin:v0.13.0
    container_name: tiles
    environment:
      DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}
    command: ['--auto-bounds=calc']
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_bridge
  db:
    image: postgis/postgis:14-3.3-alpine
    container_name: db
    shm_size: 1gb
    environment:
      PGUSER:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    ports:
      - '5432:5432'
    volumes:
      - geodata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h ${PGHOST} -d ${PGDATABASE}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_bridge
volumes:
  geodata:
  osmfiles:
networks:
  app_bridge:
    name: app_bridge
