# This file defines the production parameters.
# Development specific parameters are defined in `docker-compose.override.yml`, see: https://docs.docker.com/compose/compose-file/13-merge/
version: "3"
services:
  geo:
    image: public.ecr.aws/n0p8j4k5/atlas/app:${GITHUB_SHA}
    extends:
      file: docker-compose.geo.yml
      service: geo
    networks:
      - app_bridge
volumes:
  osmfiles:
networks:
  app_bridge:
    name: app_bridge
    external: true
