# This file sets `development` specific parameters. See: https://docs.docker.com/compose/compose-file/13-merge/
version: "3"
services:
  geo:
    image: !reset null
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./geo:/geo

