#!/usr/bin/env node

import { saveGeojson, tile2bbox } from './util.js'

// run this function in browser to get viewport setting
function logViewport() {
  const canvas = document.getElementsByClassName('mapboxgl-canvas')[0]
  let { width, height } = canvas
  const r = window.window.devicePixelRatio
  width /= r
  height /= r
  console.log(JSON.stringify({ viewport: { width, height } }, null, 2))
}

// config for https://radverkehrsatlas.de/regionen/bb?map=11/52.397/13.034&config=!(i~poi~a~~sc~!(i~poi~s~!(i~hidden~a~_F)(i~default~a)(i~education~a~_F))(i~poiPlaces~s~!(i~hidden~a~_F)(i~default~a)(i~circle~a~_F))(i~poiBoundaries~s~!(i~hidden~a)(i~default~a~_F)(i~category*_district*_label~a~_F)(i~category*_municipality~a~_F)(i~category*_municipality*_label~a~_F))(i~poiPlusBarriers~s~!(i~default~a~_F))(i~poiPlusLanduse~s~!(i~default~a~_F))(i~poiPlusPublicTransport~s~!(i~default~a~_F)))(i~bikelanes~a~_F~sc~!(i~bikelanes~s~!(i~hidden~a~_F)(i~default~a)(i~details~a~_F)(i~width~a~_F))(i~bikelanes*_plus*_presence~s~!(i~default~a~_F))(i~bikelanes*_plus*_width~s~!(i~default~a~_F))(i~bikelanes*_plus*_surface*_smoothness~s~!(i~default~a~_F))(i~bikelanes*_plus*_signs~s~!(i~default~a~_F))(i~bikelanes*_plus*_routes~s~!(i~default~a~_F)))(i~roads~a~_F~sc~!(i~roads~s~!(i~hidden~a~_F)(i~default~a)(i~sidestreets~a~_F)(i~mainstreets~a~_F))(i~maxspeed~s~!(i~hidden~a)(i~default~a~_F)(i~below30~a~_F)(i~above40~a~_F))(i~roads*_plus*_footways~s~!(i~default~a~_F)))(i~surface~a~_F~sc~!(i~surfaceRoads~s~!(i~hidden~a~_F)(i~default~a)(i~bad~a~_F))(i~surfaceBikelanes~s~!(i~hidden~a)(i~default~a~_F)(i~bad~a~_F)))(i~bicycleParking~a~_F~sc~!(i~bicycleParking~s~!(i~hidden~a~_F)(i~default~a)))(i~mapillary~a~_F~sc~!(i~mapillaryCoverage~s~!(i~hidden~a~_F)(i~default~a)(i~all~a~_F)(i~age~a~_F)(i~pano~a~_F)))~
// on vivaldi/linux at 125% display zoom
const config = {
  // viewport setting generated by logViewport()
  viewport: {
    width: 1501,
    height: 656,
  },
  map: {
    lat: 52.397,
    lng: 13.034,
    zoomFrom: 11,
    zoomTo: 11,
  },
  urls: ['/places/{z}/{x}/{y}'],
}

// requests copied from network tab
const paths = [
  '/places/11/1099/672',
  '/places/11/1098/672',
  '/places/11/1097/672',
  '/places/11/1099/673',
  '/places/11/1096/673',
  '/places/11/1096/672',
  '/places/11/1098/673',
  '/places/11/1097/673',
]

const tiles = paths.map((path) => {
  const [_1, _2, z, x, y] = path.split('/').map((s) => Number(s))
  return {
    coords: [x, y, z],
    zoom: z,
    url: path,
  }
})

saveGeojson(tiles, 'browser.geojson')
